### ISSUE TITLE
format new web site code.

### ISSUE THREAD

**Issue by ShannonDing** [apache/rocketmq-site#184]
format new web site code:
- remove useless file
- fix travis ci
- update docusaurus version to  stable release

**Comment by ShannonDing** [comment]
wait to complete.

**Comment by vongosling** [comment]
Did you discuss this in the community?

**Comment by ShannonDing** [comment]
> Did you discuss this in the community?

At present, the new official website is still in the development stage of a special branch. Currently, I am doing the test preparation work for the release version and the preparation work before the discussion. I will follow the process and decide to activate the new official website after the community discussion and voting. .
