### ISSUE TITLE
语言不对、版本位置是不是也不对？

### ISSUE THREAD

**Issue by tonycody** [apache/rocketmq-site#211]
![image](https://user-images.githubusercontent.com/6773121/188617519-2367c787-5b1a-4cc3-9655-08425900e6d6.png)
![image](https://user-images.githubusercontent.com/6773121/188617571-ceb7d9ac-aa4e-4ebc-8cf6-cbb47520e129.png)

**Comment by duhenglucky** [comment]
感谢指出，有兴趣的话可以提交个PR 修复一下，提交到new-official-website 这个分支，合入后会自动发布构建的

**Comment by tonycody** [comment]
> 感谢指出，有兴趣的话可以提交个PR 修复一下，提交到new-official-website 这个分支，合入后会自动发布构建的

我有个疑问，为什么不直接使用 docusaurus 呢？现在的这个网格和 docusaurus 没有区别。完全一致，包括目前提供的功能。

如果是 docusaurus 固定的套路，改下容易。但这个改一下，大多数非专业前端搞不定。目的是相同的~~~

**Comment by tonycody** [comment]
> 感谢指出，有兴趣的话可以提交个PR 修复一下，提交到new-official-website 这个分支，合入后会自动发布构建的
使用 docusaurus 的开源项目比比皆是。

https://apisix.apache.org/
https://reactnative.dev/

**Comment by lizhanhui** [comment]
@tonycody 我看了下代码，这个分支就是用docusaurus配置生成的

**Comment by tonycody** [comment]
> @tonycody 我看了下代码，这个分支就是用docusaurus配置生成的. https://github.com/apache/rocketmq-site/blob/new-official-website/docusaurus.config.js

这个搞不来~既然用一样的，常规方案不香吗？

**Comment by tonycody** [comment]
不清楚是不是基于什么情况考虑的

**Comment by tonycody** [comment]
我看错了分支了~

**Comment by tonycody** [comment]
> @tonycody 我看了下代码，这个分支就是用docusaurus配置生成的. https://github.com/apache/rocketmq-site/blob/new-official-website/docusaurus.config.js

我看错了分支了。应该是新的是基于 docusaurus 的

**Comment by tonycody** [comment]
忽略吧~

**Comment by lizhanhui** [comment]
@tonycody  现在这个分支还有不少问题，包括功能性的，语言对齐，翻译错误，格式表述等，欢迎帮助改进
