### ISSUE TITLE
Add multiple language support.

### ISSUE THREAD

**Issue by jackytsu** [apache/rocketmq-site#22]
Add multiple language support.

**Comment by zhangjing9898** [comment]
在 why RocketMQ这篇document中，可以加上rocketMQ和kafka的区别，比如：
- rocketMQ是阿里开源的一款消息队列，rocketMQ具有很多其他消息队列不具有的特性，其实可以跟kafka做一个对比图，比如:
  + 在Kafka中，是1个topic有多个partition，每个partition有1个master + 多个slave。在RocketMQ里面，1台机器只能要么是Master，要么是Slave
  + Kafka是先有Broker，然后产生出Master/Slave；RokcetMQ是先定义Master/Slave，然后组合出Broker。
  
其实，这些diff都可以罗列出来，让读者更加明确的明白，为什么选择rocketMQ，而不是其他的。

**Comment by ShannonDing** [comment]
close due to new rocketmq site.
