### ISSUE TITLE
Translation for "Deployment-Admin Tool" Section in the v4.x & 5.0 Document (CN -> EN)

### ISSUE THREAD

**Issue by tsunghanjacktsai** [apache/rocketmq-site#279]
The Chinese version of the "Deployment-Admin Tool" section in the v4.x & v5.0 document has now been finished. However, its English version is still incomplete.

We now require someone who knows both Chinese and English and understands the technical terms of Apache RocketMQ to build it. The translation work is not only copy/paste from translation tools but also requires you to have some basic knowledge of Apache RocketMQ and technical writing.

**Comment by mxsm** [comment]
I will submit a PR to do it
