### ISSUE TITLE
Wrong format in 5.x doc

### ISSUE THREAD

**Issue by zhiliatom** [apache/rocketmq-site#284]
1. Please describe the issue you observed:

![image](https://user-images.githubusercontent.com/87265072/192768609-ef243621-3274-417a-94a1-9f4ea90e7487.png)

Version 4.0 looks good, but version 5.0 displays abnormally，someone who is capable can fix it

**Comment by tsunghanjacktsai** [comment]
Hi @zhiliatom ,

Thx for pointing out the issue. I believe this has been fixed in this PR: https://github.com/apache/rocketmq-site/pull/277 . However, it seems like didn't take effect due to the build failure. We'll fix it later.

**Comment by zhiliatom** [comment]
> Hi @zhiliatom ,
> 
> Thx for pointing out the issue. I believe this has been fixed in this PR: #277 . However, it seems like didn't take effect due to the build failure. We'll fix it later.

Thx for your reply, I' ll close this issue
