### ISSUE TITLE
Translation for "常见问题解答" Section in the v4.x & 5.0 Document (CN -> EN)

### ISSUE THREAD

**Issue by tsunghanjacktsai** [apache/rocketmq-site#295]
The Chinese version of the "常见问题解答" section in the v4.x & v5.0 document has now been finished. However, its English version is still incomplete.

We now require someone who knows both Chinese and English and understands the technical terms of Apache RocketMQ to build it. The translation work is not only copy/paste from translation tools but also requires you to have some basic knowledge of Apache RocketMQ and technical writing.

**Comment by Oliverwqcwrw** [comment]
Hello @tsunghanjacktsai ,

I have participated the hacktoberfest and interested in this issue ,

I want to try it, Could  you please assign it to me?
