### ISSUE TITLE
Translation for "代码指南" Section in the v4.x & 5.0 Document (CN -> EN)

### ISSUE THREAD

**Issue by tsunghanjacktsai** [apache/rocketmq-site#297]
The Chinese version of the "代码指南" section in the v4.x & v5.0 document has now been finished. However, its English version is still incomplete.

We now require someone who knows both Chinese and English and understands the technical terms of Apache RocketMQ to build it. The translation work is not only copy/paste from translation tools but also requires you to have some basic knowledge of Apache RocketMQ and technical writing.

**Comment by nowinkeyy** [comment]
I want to try it. While file should i submit to the new-official-website branch? Or any other position?

**Comment by nowinkeyy** [comment]
> I want to try it. Which file should i submit to the new-official-website branch? Or any other position?

I found the place.
