### ISSUE TITLE
Translation for "Contribution Guide-发布手册" Section in the v4.x & 5.0 Document (CN -> EN)

### ISSUE THREAD

**Issue by tsunghanjacktsai** [apache/rocketmq-site#299]
The Chinese version of the "Contribution Guide-发布手册" section in the v4.x & v5.0 document has now been finished. However, its English version is still incomplete.

We now require someone who knows both Chinese and English and understands the technical terms of Apache RocketMQ to build it. The translation work is not only copy/paste from translation tools but also requires you to have some basic knowledge of Apache RocketMQ and technical writing.

**Comment by FadePeople** [comment]
Can I try it on?
