### ISSUE TITLE
word error in doc for chinese at : 文档/生产者/基本概念 => "可以支持不用的应用场景" should be => "可以支持不同的应用场景" 

### ISSUE THREAD

**Issue by taopanwoaini** [apache/rocketmq-site#306]
word error in doc for chinese at : 文档/生产者/基本概念 => "可以支持不用的应用场景" should be => "可以支持不同的应用场景" ;

The great difference between the two words is easy to cause misunderstanding;

两个词意思相差比较大, 容易造成误解;

![image](https://user-images.githubusercontent.com/32383665/193980121-265b50cc-c195-4cf1-b17a-6a414caccf16.png)

**Comment by ShannonDing** [comment]
close due to #308
