### ISSUE TITLE
Keep the context in the same format

### ISSUE THREAD

**Issue by nowinkeyy** [apache/rocketmq-site#313]
**To use the same format and words**

![1665315180369](https://user-images.githubusercontent.com/72536832/194754597-ed977072-5795-400f-8c8d-fa19f944be5a.png)

**Comment by nowinkeyy** [comment]
Hi @ShannonDing 
Is this issue part of hacktoberfest?

**Comment by tsunghanjacktsai** [comment]
> Hi @ShannonDing Is this issue part of hacktoberfest?

@nowinkeyy Would later label this as the hacktoberfest issue. You could hold on a moment.
