### ISSUE TITLE
Error index of folder.

### ISSUE THREAD

**Issue by GOODBOY008** [apache/rocketmq-site#324]
<img width="221" alt="企业微信截图_16655601232783" src="https://user-images.githubusercontent.com/13617900/195279772-ad418e02-cbd5-4a6e-a4ba-b335dcfcb5a1.png">

**Comment by GOODBOY008** [comment]
I will fix in this issue https://github.com/apache/rocketmq-site/issues/311.

**Comment by Oliverwqcwrw** [comment]
close as merged
