### ISSUE TITLE
Incorrect usage of updatetopic in quickstart

### ISSUE THREAD

**Issue by WesleyOne** [apache/rocketmq-site#394]
RocketMQ版本5.0.0
 
中/英文的快速开始章节的如下位置updatetopic命令使用有误。
https://rocketmq.apache.org/zh/docs/quickStart/02quickstart
5.SDK测试消息收发
```
$ sh bin/mqadmin updatetopic -n localhost:9876 -t TestTopic
```
执行后，返回的命令使用介绍，没有创建topic。如图：
<img width="919" alt="截屏2022-12-08 22 33 19" src="https://user-images.githubusercontent.com/24919538/206477677-fd907505-4cb1-4b59-a8fe-9467d95cffe8.png">

看源码`org.apache.rocketmq.tools.command.topic.UpdateTopicSubCommand#execute`，确认`updatetopic`必须指定`-b`Broker地址或`-c`集群名称，在本章节可以改成指定默认集群名称解决问题，如下命令：
```
sh bin/mqadmin updatetopic -n localhost:9876 -t TestTopic -c DefaultCluster
```
测试可行，如图：
<img width="1071" alt="截屏2022-12-08 22 37 18" src="https://user-images.githubusercontent.com/24919538/206478058-46b252d0-61be-446c-a928-3f55e394cfa6.png">

**Comment by chenzlalvin** [comment]
already fixed
