### ISSUE TITLE
句意不正确

### ISSUE THREAD

**Issue by yuluo-yx** [apache/rocketmq-site#529]
https://rocketmq.apache.org/zh/docs/domainModel/01main

Apache RocketMQ 的最小传输单元。消息具备不可变性，在初始化发送和完成存储后即不可变。

下面这句话是否有问题？
储后**即不可变**

**Comment by chenzlalvin** [comment]
消息包含的信息包括生产者构建的业务信息以及存储端补充一些系统信息，所以在存储完成后业务信息和系统信息均已完成初始化，后续不再有更改。
