### ISSUE TITLE
微信二维码过期

### ISSUE THREAD

**Issue by yuluo-yx** [apache/rocketmq-site#536]
url：https://rocketmq.apache.org/contact
此右面中提供的微信二维码扫描显示过期！

**Comment by yuluo-yx** [comment]
另外，rocketmq社区是否有相关的钉钉或者微信讨论群？可以提供一下群号吗？

**Comment by chenzlalvin** [comment]
二维码会去掉，直接搜索微信公众号，钉钉群：21982288
