### ISSUE TITLE
Default value of DefaultMQPushConsumer.consumeMessageBatchMaxSize is wrong in document

### ISSUE THREAD

**Issue by Coder-Shaw** [apache/rocketmq-site#540]
文档地址：https://rocketmq.apache.org/zh/docs/4.x/parameterConfiguration/01local#defaultmqpushconsumer%E9%85%8D%E7%BD%AE

其中“DefaultMQPushConsumer配置”表格内容中，consumeMessageBatchMaxSize的默认值标注错误，客户端代码中默认值为1，文档中标注为-1。

**Comment by caigy** [comment]
@Coder-Shaw Good catch~ Would you like to submit a PR to fix it?
