### ISSUE TITLE
英文文档描述有问题

### ISSUE THREAD

**Issue by xrz-baizer** [apache/rocketmq-site#602]
<img width="952" alt="image" src="https://github.com/apache/rocketmq-site/assets/48161253/906ee437-bda1-4c8b-a46d-5f0102edf78e">

**Comment by xrz-baizer** [comment]
[i18n/en/docusaurus-plugin-content-docs/current/01-introduction/03whatis.md](https://github.com/apache/rocketmq-site/blob/new-official-website/i18n/en/docusaurus-plugin-content-docs/current/01-introduction/03whatis.md)

**Comment by lizhanhui** [comment]
@397047243 图片应该更新过，翻译没有跟进。
